# constants for cardea helper 
ASSAY = 'assay'
CARDEA_URL = 'cardea_url'
DONOR = 'donor'
TUMOUR_ID = 'tumour_id'
NORMAL_ID = 'normal_id'
PATIENT_ID = 'patient_study_id'
PROJECT = 'project'
PROVENANCE_ID = 'provenance_id'
REQ_APPROVED = 'requisition_approved'
REQ_ID = 'requisition_id'
SAMPLE_NAME_TUMOUR = 'sample_name_tumour'
SAMPLE_NAME_NORMAL = 'sample_name_normal'
SAMPLE_NAME_AUX = 'sample_name_aux'
