# constants for cardea helper 
ASSAY = 'assay'
CARDEA_URL = 'cardea_url'
DONOR = 'donor'
TUMOUR_ID = 'tumour_id'
NORMAL_ID = 'normal_id'
PATIENT_ID = 'patient_study_id'
PROJECT = 'project'
PROVENANCE_ID = 'provenance_id'
REQ_APPROVED = 'requisition_approved'
REQ_ID = 'requisition_id'
SAMPLE_NAME_WHOLE_GENOME_TUMOUR = 'sample_name_whole_genome_tumour'
SAMPLE_NAME_WHOLE_GENOME_NORMAL = 'sample_name_whole_genome_normal'
SAMPLE_NAME_WHOLE_TRANSCRIPTOME = 'sample_name_whole_transcriptome'
