from djerba import __version__

##LINKS
ARRIBA_LINK="https://github.com/suhrig/arriba"
BWAMEM_LINK="https://bio-bwa.sourceforge.net/"
CONSENSUSCRUNCHER_LINK="https://github.com/pughlab/ConsensusCruncher"
DJERBA_LINK="https://github.com/oicr-gsi/djerba"
GATK_LINK="https://gatk.broadinstitute.org/hc/en-us/sections/360008481611-4-1-6-0"
ICHORCNA_LINK="https://github.com/broadinstitute/ichorCNA"
MANE_LINK="https://www.ncbi.nlm.nih.gov/refseq/MANE/#Select"
MAVIS_LINK="https://github.com/bcgsc/mavis"
MICROSATELLITE_LINK="https://www.sciencedirect.com/science/article/pii/S1672022920300218"
MRDETECT_LINK="https://pubmed.ncbi.nlm.nih.gov/32483360/"
MUTECT2_LINK="https://gatk.broadinstitute.org/hc/en-us/articles/5358911630107-Mutect2"
ONCOKB_LINK="https://api.oncokb.org/oncokb-annotator/gene-annotation"
PICARD_LINK="https://gatk.broadinstitute.org/hc/en-us/articles/360037052812-MarkDuplicates-Picard-"
REFERENCE_GENOME_LINK="https://www.ncbi.nlm.nih.gov/assembly/GCF_000001405.38/"
RSEM_LINK="https://github.com/deweylab/RSEM"
SEQUENZA_LINK="https://doi.org/10.1093/annonc/mdu479"
STAR_LINK="https://github.com/alexdobin/STAR"
STARFUSION_LINK="https://github.com/STAR-Fusion/STAR-Fusion/wiki"
VARIANTEFFECTPREDICTOR_LINK="https://useast.ensembl.org/info/docs/tools/vep/index.html"

##VERSIONS
ARRIBA_VERSION="2.4.0"
BWAMEM_VERSION="0.7.12"
CONSENSUSCRUNCHER_VERSION=""
DJERBA_VERSION=__version__
GATK_VERSION="4.1.6.0"
ICHORCNA_VERSION=""
ILLUMINA_VERSION="NovaSeq 6000"
TAR_ILLUMINA_VERSION="NextSeq 550"
MANE_VERSION="1.0"
MAVIS_VERSION="2.2.6"
MICROSATELLITE_VERSION="1.2.0"
MRDETECT_VERSION="1.0"
MUTECT2_VERSION="4.2.6.1"
PICARD_VERSION="2.21.2"
REFERENCE_GENOME_VERSION="GRCh38.p12"
RSEM_VERSION="1.3.3"
SEQUENZA_VERSION="2.1.2"
STAR_VERSION="2.7.10b"
STARFUSION_VERSION="1.8.1"
SUPPLEMENT_DJERBA_VERSION="0.1"
VARIANTEFFECTPREDICTOR_VERSION="105.0"
PIPELINE_VERSION = "4.0"
