# top-level variable names
CTDNA_OUTCOME = 'outcome'
TUMOUR_FRACTION = 'TF'            
SITES_CHECKED = 'sites_checked'
READS_CHECKED = 'reads_checked'
SITES_DETECTED = 'sites_detected'
READS_DETECTED = 'reads_detected' 
PVALUE = 'p-value'    
SIGNIFICANCE = 'significance_text'       
COHORT_N = 'hbc_n'
DETECTION_PLOT = 'detection_plot'
RESULTS = 'results'