"""Field names for the input INI file"""

# section names
INPUTS = 'inputs'
SETTINGS = 'settings'
DISCOVERED = 'discovered'

# parameter names
BED_PATH = 'bed_path'
DATA_DIR = 'data_dir'
ENSCON = 'enscon'
ENTCON = 'entcon'
GAMMA = 'gamma'
GENEBED = 'genebed'
GENELIST = 'genelist'
MAF_FILE = 'maf_file'
METRICS_FILENAME = 'metrics_filename'
METRICS_SCHEMA = 'metrics_schema'
MUTATION_NONSYN = 'mutation_nonsyn'
NORMAL_ID = 'normalid'
ONCOLIST = 'oncolist'
OUT_DIR = 'out_dir'
PATIENT = 'patient'
PATIENT_ID = 'patientid'
PROVENANCE = 'provenance'
R_SCRIPT_DIR = 'r_script_dir'
REQUIRE_COMPLETE = 'require_complete'
SEQUENZA_FILE = 'sequenza_file'
STUDY_ID = 'studyid'
TMBCOMP = 'tmbcomp'
VALIDATE = 'validate'
WORK_DIR = 'work_dir'
