# collection of constants to represent OncoKB levels

LEVEL_1 = 'LEVEL_1'
LEVEL_2 = 'LEVEL_2'
LEVEL_3A = 'LEVEL_3A'
LEVEL_3B = 'LEVEL_3B'
LEVEL_4 = 'LEVEL_4'
LEVEL_R1 = 'LEVEL_R1'
LEVEL_R2 = 'LEVEL_R2'
ONCOGENIC = 'Oncogenic'
LIKELY_ONCOGENIC = 'Likely Oncogenic'
UNKNOWN = 'Unknown'

FDA_APPROVED_LEVELS = [LEVEL_1, LEVEL_2, LEVEL_R1]
INVESTIGATIONAL_LEVELS = [LEVEL_3A, LEVEL_3B, LEVEL_4, LEVEL_R2]
THERAPY_LEVELS = [
    LEVEL_1,
    LEVEL_2,
    LEVEL_3A,
    LEVEL_3B,
    LEVEL_4,
    LEVEL_R1,
    LEVEL_R2,
]
ORDERED_LEVELS = [
    LEVEL_1,
    LEVEL_2,
    LEVEL_3A,
    LEVEL_3B,
    LEVEL_4,
    LEVEL_R1,
    LEVEL_R2,
    ONCOGENIC,
    LIKELY_ONCOGENIC,
    UNKNOWN
]
