"""Constants for use across multiple Djerba classes"""

DATA_DIR_NAME = 'data'
SEQUENZA_GAMMA = 'sequenza_gamma'
SEQUENZA_PURITY_KEY = 'SEQUENZA_PURITY_FRACTION'
SEQUENZA_PLOIDY_KEY = 'SEQUENZA_PLOIDY'
READER_CLASS_KEY = 'reader_class'
TEXT_ENCODING = 'utf-8'
TMB_PER_MB_KEY = 'TMB_PER_MB'

# Gene attributes from Elba schema
ALLELE_FRACTION_PERCENTILE = 'Allele_Fraction_Percentile'
CHROMOSOME = 'Chromosome'
COPY_STATE = 'Copy_State'
DRUG_ANNOTATION = 'Drug_Annotation'
EXP_PERCENTILE = 'Exp_Percentile'
EXP_Z_SCORE = 'Exp_Z_Score'
FDA_APPROVED_TREATMENT = 'FDA_Approved_Treatment'
FUSION = 'Fusion'
GENE = 'Gene'
GENE_ANNOTATION = 'Gene_Annotation'
MUTATION_CLASS = 'Mutation_Class'
ONCOGENIC_BINARY = 'Oncogenic_Binary'
ONCOKB = 'OncoKB'
PROTEIN_CHANGE = 'Protein_Change'
VARIANT_READS_AND_TOTAL_READS = 'Variant_Reads_And_Total_Reads'
VARIANT_CLASSIFICATION = 'Variant_Classification'
WHIZBAM_URL = 'Whizbam_URL'

# script mode names
CONFIGURE = 'configure'
EXTRACT = 'extract'
HTML = 'html'
PDF = 'pdf'
ALL = 'all'
