"""
This file contains a list of constants to be used in the TAR SNV Indel plugin.
"""

# For rendering
TOTAL_VARIANTS = 'Total variants'
CLINICALLY_RELEVANT_VARIANTS = 'Clinically relevant variants'
BODY = 'Body'
HAS_EXPRESSION_DATA = 'Has expression data'
EXPRESSION_METRIC = 'Expression Percentile'
GENE = 'Gene'
GENE_URL = 'Gene_URL'
CHROMOSOME = 'Chromosome'
DEPTH = 'Depth'
ALTERATION = 'Alteration'
ONCOKB = 'OncoKB'
CNV_PLOT = 'cnv_plot'
TEXT_ENCODING = 'utf-8'
PROTEIN = 'Protein'
PROTEIN_URL = 'Protein_URL'
MUTATION_TYPE = 'Type'
VAF_PERCENT = 'VAP (%)'
VAF_NOPERCENT = 'VAF'
TUMOUR_DEPTH = 't_depth'
TUMOUR_ALT_COUNT = 't_alt_count'
COPY_STATE = 'Copy State'
LOH_STATE = 'LOH (ABratio)'
ONCOKB = 'OncoKB'
VAF_PLOT = 'vaf_plot'
TMB_TOTAL = 'Tumour Mutation Burden'
